language: node_js
sudo: false
node_js:
  - "4"
  - "5"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/webdriver-manager update
  - nohup bash -c "./node_modules/.bin/webdriver-manager start 2>&1 &"
  - nohup bash -c "npm start 2>&1 &"

script:
  - TEST_BROWSER_NAME=firefox npm test
